#!/bin/bash
echo ..........................................................
echo Username: destiny
echo Password: password
echo ..........................................................
echo Script by your favorite cybersec dev Moujira!
