#!/bin/bash
echo ..........................................................
echo Username: runneradmin
echo Password: P@ssw0rd!
echo ..........................................................
echo Script by your favorite cybersec dev Moujira!
